export const GET_USERS_PRODUCTS = 'GET_USERS_PRODUCTS';
export const ADD_USERS_PRODUCTS = 'ADD_USERS_PRODUCTS';
export const UPDATE_USERS_PRODUCTS = 'UPDATE_USERS_PRODUCTS';
export const DELETE_USERS_PRODUCTS = 'DELETE_USERS_PRODUCTS';
export const GET_USER = 'GET_USER';
export const SET_USER = 'SET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
export const SET_USERS = 'SET_USERS';
export const UPDATE_USERS = 'UPDATE_USERS';
export const DELETE_USERS = 'DELETE_USERS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS'
export const SET_PRODUCTS = 'SET_PRODUCTS';
export const ADD_PRODUCTS = 'SET_PRODUCTS';
export const UPDATE_PRODUCTS = 'UPDATE_PRODUCTS';
export const DELETE_PRODUCTS = 'DELETE_PRODUCTS';

