export const GET_USERS_PRODUCTS = 'GET_USERS_PRODUCTS';
export const ADD_USERS_PRODUCTS = 'ADD_USERS_PRODUCTS';
export const UPDATE_USERS_PRODUCTS = 'UPDATE_USERS_PRODUCTS';
export const DELETE_USERS_PRODUCTS = 'DELETE_USERS_PRODUCTS';
export const GET_USER = 'GET_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const DELETE_USER = 'DELETE_USER';
export const GET_USERS = 'GET_USERS';
export const SET_USER_DETAILS = 'SET_USER_DETAILS'

export const SET_USERS = 'SET_USERS';
export const ADD_USERS = 'ADD_USERS';
export const ADD_USERS_ERROR = 'ADD_USERS_ERROR';
export const USERS_ERROR_RESET = 'USERS_ERROR_RESET';
export const UPDATE_USERS = 'UPDATE_USERS';
export const DELETE_USERS = 'DELETE_USERS';


export const SET_CLIENTS = 'SET_CLIENTS';
export const ADD_CLIENTS = 'ADD_CLIENTS';
export const ADD_CLIENTS_ERROR = 'ADD_CLIENTS_ERROR';
export const CLIENTS_ERROR_RESET = 'CLIENTS_ERROR_RESET';
export const UPDATE_CLIENTS = 'UPDATE_CLIENTS';
export const DELETE_CLIENTS = 'DELETE_CLIENTS';

