import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { Client, Person } from 'src/app/modals/users';

@Component({
  selector: 'app-form-client',
  templateUrl: './form-client.component.html',
  styleUrls: ['./form-client.component.css']
})
export class FormClientComponent implements OnInit {
  @Input() client:Client
  @Input() currentUser:Person
  @Input() action:string
  @Input() clientView:string
  @Output() cv:EventEmitter<any>=new EventEmitter()
  @Output() cc:EventEmitter<any> =new EventEmitter()
  @Output() pc:EventEmitter<any> =new EventEmitter()
  genders=["Male", "Female"]
  types=[ "CS Client", "LBF Client"]
  employers = ['ABIM DISTRICT', 'ADJUMANI DISTRICT', 'AGAGO DISTRICT', 'ALEBTONG DISTRICT', 'AMOLATAR DISTRICT', 'AMUDAT DISTRICT', 'AMURIA DISTRICT', 'AMURU DISTRICT', 'APAC DISTRICT', 'APAC MUNICIPAL COUNCIL', 'ARUA CITY', 'ARUA DISTRICT', 'ARUA HOSPITAL', 'BUDAKA DISTRICT', 'BUDUDA DISTRICT', 'BUGIRI DISTRICT', 'BUGIRI MUNICIPAL COUNCIL', 'BUGWERI DISTRICT', 'BUHWEJU DISTRICT', 'BUIKWE DISTRICT', 'BUKEDEA DISTRICT', 'BUKOMANSIMBI DISTRICT', 'BUKWO DISTRICT', 'BULAMBULI DISTRICT', 'BULIISA DISTRICT', 'BUNDIBUGYO DISTRICT', 'BUNYANGABU DISTRICT', 'BUSHENYI DISTRICT', 'BUSIA DISTRICT', 'BUSIA MUNICIPAL COUNCIL', 'BUSITEMA UNIVERSITY', 'BUTABIKA HOSPITAL', 'BUTALEJA DISTRICT', 'BUTAMBALA DISTRICT', 'BUTEBO DISTRICT', 'BUVUMA DISTRICT', 'BUYENDE DISTRICT', 'COURTS OF JUDICATURE', 'DAIRY DEVELOPMENT AUTHORITY', 'DIRECTORATE OF CITIZENSHIP AND IMMIGRATION CONTROL', 'DIRECTORATE OF ETHICS AND INTEGRITY', 'DIRECTORATE OF GOVERNMENT ANALYTICAL LABORATORIES', 'DIRECTORATE OF PUBLIC PROSECUTION', 'DOKOLO DISTRICT', 'ELECTORAL COMMISSION', 'ENTEBBE MUNICIPAL COUNCIL', 'ENTEBBE REGIONAL REFERRAL HOSPITAL', 'EQUAL OPPORTUNITIES COMMISSION', 'FORT PORTAL CITY', 'FORT PORTAL HOSPITAL', 'GOMBA DISTRICT', 'GULU CITY', 'GULU DISTRICT', 'GULU HOSPITAL', 'GULU UNIVERSITY', 'HEALTH SERVICE COMMISSION', 'HOIMA CITY', 'HOIMA DISTRICT', 'HOIMA HOSPITAL', 'HOIMA MUNICIPAL COUNCIL', 'IBANDA DISTRICT', 'IBANDA MUNICIPAL COUNCIL', 'IGANGA DISTRICT', 'IGANGA MUNICIPAL COUNCIL', 'INSPECTORATE OF GOVERNMENT', 'ISINGIRO DISTRICT', 'JINJA CITY', 'JINJA DISTRICT', 'JINJA HOSPITAL', 'KAABONG DISTRICT', 'KABALE DISTRICT', 'KABALE HOSPITAL', 'KABALE MUNICIPAL COUNCIL', 'KABALE UNIVERSITY', 'KABAROLE DISTRICT', 'KABERAMAIDO DISTRICT', 'KAGADI DISTRICT', 'KAKUMIRO DISTRICT LOCAL GOVERNMENT', 'KALAKI DISTRICT', 'KALANGALA DISTRICT', 'KALIRO DISTRICT', 'KALUNGU DISTRICT', 'KAMPALA CAPITAL CITY AUTHORITY', 'KAMULI DISTRICT', 'KAMULI MUNICIPAL COUNCIL', 'KAMWENGE DISTRICT', 'KANUNGU DISTRICT', 'KAPCHORWA DISTRICT', 'KAPCHORWA MUNICIPAL COUNCIL', 'KAPELEBYONG DISTRICT', 'KARENGA DISTRICT', 'KASANDA DISTRICT', 'KASESE DISTRICT', 'KASESE MUNICIPAL COUNCIL', 'KATAKWI DISTRICT', 'KAWEMPE REFERRAL HOSPITAL', 'KAYUNGA DISTRICT', 'KAZO DISTRICT', 'KIBAALE DISTRICT', 'KIBOGA DISTRICT', 'KIBUKU DISTRICT', 'KIKUUBE DISTRICT', 'KIRA MUNICIPAL COUNCIL', 'KIRUDDU REFERRAL HOSPITAL', 'KIRUHURA DISTRICT', 'KIRYANDONGO DISTRICT', 'KISORO DISTRICT', 'KISORO MUNICIPAL COUNCIL', 'KITAGWENDA DISTRICT', 'KITGUM DISTRICT', 'KITGUM MUNICIPAL COUNCIL', 'KOBOKO DISTRICT', 'KOBOKO MUNICIPAL COUNCIL', 'KOLE DISTRICT', 'KOTIDO DISTRICT', 'KOTIDO MUNICIPAL COUNCIL', 'KUMI DISTRICT', 'KUMI MUNICIPAL COUNCIL', 'KWANIA DISTRICT', 'KWEEN DISTRICT', 'KYAMBOGO UNIVERSITY', 'KYANKWANZI DISTRICT', 'KYEGEGWA DISTRICT', 'KYENJOJO DISTRICT', 'KYOTERA DISTRICT', 'LAMWO DISTRICT', 'LAW REFORM COMMISSION', 'LIRA CITY', 'LIRA DISTRICT', 'LIRA HOSPITAL', 'LIRA UNIVERSITY', 'LOCAL GOVERNMENT FINANCE COMMISSION', 'LUGAZI MUNICIPAL COUNCIL', 'LUUKA DISTRICT', 'LUWERO DISTRICT', 'LWENGO DISTRICT', 'LYANTONDE DISTRICT', 'MADI-OKOLLO DISTRICT', 'MAKERERE UNIVERSITY', 'MAKERERE UNIVERSITY BUSINESS SCHOOL', 'MAKINDYE SSABAGABO MUNICIPAL COUNCIL', 'MANAFWA DISTRICT', 'MARACHA DISTRICT', 'MASAKA CITY', 'MASAKA DISTRICT', 'MASAKA HOSPITAL', 'MASAKA MUNICIPAL COUNCIL', 'MASINDI DISTRICT', 'MASINDI MUNICIPAL COUNCIL', 'MAYUGE DISTRICT', 'MBALE CITY', 'MBALE DISTRICT', 'MBALE HOSPITAL', 'MBALE MUNICIPAL COUNCIL', 'MBARARA CITY', 'MBARARA HOSPITAL', 'MBARARA MUNICIPAL COUNCIL', 'MBARARA UNIVERSITY OF SCIENCE AND TECHNOLOGY', 'MINISTRY OF AGRICULTURE, ANIMAL INDUSTRY AND FISHERIES', 'MINISTRY OF DEFENSE AND VETERANS AFFAIRS', 'MINISTRY OF EAST AFRICAN AFFAIRS', 'MINISTRY OF EDUCATION AND SPORTS', 'MINISTRY OF ENERGY AND MINERAL DEVELOPMENT', 'MINISTRY OF FOREIGN AFFAIRS', 'MINISTRY OF GENDER, LABOR AND SOCIAL DEVELOPMENT', 'MINISTRY OF HEALTH', 'MINISTRY OF INTERNAL AFFAIRS', 'MINISTRY OF JUSTICE AND CONSTITUTIONAL AFFAIRS', 'MINISTRY OF LANDS, HOUSING AND URBAN DEVELOPMENT', 'MINISTRY OF SCIENCE, TECHNOLOGY AND INNOVATION', 'MINISTRY OF TOURISM AND WILDLIFE', 'MINISTRY OF TRADE AND INDUSTRY', 'MINISTRY OF WATER AND ENVIRONMENT', 'MINISTRY OF WORKS AND TRANSPORT', 'MITOOMA DISTRICT', 'MITYANA DISTRICT', 'MITYANA MUNICIPAL COUNCIL', 'MOROTO DISTRICT', 'MOROTO HOSPITAL', 'MOROTO MUNICIPAL COUNCIL', 'MOYO DISTRICT', 'MPIGI DISTRICT', 'MUBENDE DISTRICT', 'MUBENDE HOSPITAL', 'MUBENDE MUNICIPAL COUNCIL', 'MUKONO DISTRICT', 'MUKONO MUNICIPAL COUNCIL', 'MULAGO HOSPITAL COMPLEX', 'MULAGO SPECIALISED WOMEN AND NEONATAL HOSPITAL', 'MUNI UNIVERSITY', 'NABILATUK DISTRICT', 'NAGURU-CHINA FRIENDSHIP HOSPITAL', 'NAKAPIRIPIRITI DISTRICT', 'NAKASEKE DISTRICT', 'NAKASONGOLA DISTRICT', 'NAMAYINGO DISTRICT', 'NAMISINDWA DISTRICT', 'NAMUTUMBA DISTRICT', 'NANSANA MUNICIPAL COUNCIL', 'NAPAK DISTRICT', 'NATIONAL ENVIRONMENT MANAGEMENT AUTHORITY', 'NATIONAL IDENTIFICATION AND REGISTRATION AUTHORITY', 'NATIONAL POPULATION COUNCIL', 'NEBBI DISTRICT', 'NEBBI MUNICIPAL COUNCIL', 'NGORA DISTRICT', 'NJERU MUNICIPAL COUNCIL', 'NTOROKO DISTRICT', 'NTUNGAMO DISTRICT', 'NTUNGAMO MUNICIPAL COUNCIL', 'NWOYA DISTRICT', 'OBONGI DISTRICT', 'OFFICE OF THE AUDITOR GENERAL', 'OFFICE OF THE PRESIDENT', 'OFFICE OF THE PRIME MINISTER', 'OMORO DISTRICT', 'OTUKE DISTRICT', 'OYAM DISTRICT', 'PADER DISTRICT', 'PAKWACH DISTRICT', 'PALLISA DISTRICT', 'PARLIAMENTARY COMMISSION', 'RAKAI DISTRICT', 'RUBANDA DISTRICT', 'RUBIRIZI DISTRICT', 'RUKIGA DISTRICT', 'RUKUNGIRI DISTRICT', 'RUKUNGIRI MUNICIPAL COUNCIL', 'RWAMPARA DISTRICT', 'SEMBABULE DISTRICT', 'SERERE DISTRICT', 'SHEEMA DISTRICT', 'SHEEMA MUNICIPAL COUNCIL', 'SIRONKO DISTRICT', 'SOROTI CITY', 'SOROTI DISTRICT', 'SOROTI HOSPITAL', 'SOROTI UNIVERSITY', 'STATE HOUSE', 'TEREGO DISTRICT LOCAL GOVERNMENT', 'TORORO DISTRICT', 'TORORO MUNICIPAL COUNCIL', 'UGANDA AIDS COMMISSION', 'UGANDA BLOOD TRANSFUSION SERVICES', 'UGANDA CANCER INSTITUTE', 'UGANDA HEART INSTITUTE', 'UGANDA HUMAN RIGHTS COMMISSION', 'UGANDA LAND COMMISION', 'UGANDA NATIONAL ROADS AUTHORITY (UNRA)', 'UGANDA POLICE', 'UGANDA PRISONS SERVICE', 'UGANDA VIRUS RESEARCH INSTITUTE', 'WAKISO DISTRICT', 'YUMBE DISTRICT', 'ZOMBO DISTRICT']
  constructor() { }

  ngOnInit(): void {
    this.setClientType()
  }
  
  changeClientView(view:string){
    this.cv.emit(view)
  }
  clientPatch(){
    if (this.action === 'add'){
      let payload = ( ({ email,firstname,surname,dob,gender,contact1,contact2,type,status,created,employer,ipps }) =>
                      ({ email,firstname,surname,dob:JSON.stringify(dob),gender,contact1,contact2,type,status,created:JSON.stringify(created),agent:this.currentUser.id,employer,ipps}))
                    (this.client) 
      this.cc.emit(payload) // new client
    }else{
      let { fullname,agentName,days,label,...payload} = {...this.client,dob:JSON.stringify(this.client.dob), created:JSON.stringify(this.client.created)}
      console.log(payload)
      this.pc.emit(payload) //edited client
    }
  }
  setClientType(){
    if (this.currentUser.role ==='CS Agent' || this.currentUser.role ==='CS Leader'){
      this.client.type = 'CS Client'
    }else if ( this.currentUser.role ==='LBF Agent' || this.currentUser.role ==='LBF Leader'){
      this.client.type = 'LBF Client'
    }
  }
}
